main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('facilities/', views.facilities, name='facilities'),
    path('facilities/<str:facility_anemity>/', views.facility_anemity, name='facility_anemity'),
    path('reservations/', views.reservations, name='reservations'),
    path('profile/', views.update_profile, name='profile'),
    path('changepassword/', views.change_password, name='changepassword'),
    path('reservations/', views.reservations, name='reservations'),
    path('reviews/', views.reviews, name='reviews'),
    path('cancel_reservation/<int:reservation_id>/', views.cancel_reservation, name='cancel_reservation'),
     path('add_review/<int:facility_id>/', views.add_review, name='add_review'),
]

main/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm
from django.core.validators import RegexValidator
from main.models import Student, Staff, Reviews
from django import forms
from .models import Reservation

class ProfileForm(UserChangeForm):
    student_id = forms.CharField(label='Student ID', max_length=100, required=False)
    staff_id = forms.CharField(label='Staff ID', max_length=100 , required=False)
    name = forms.CharField(label='Name', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)
    profile_pic = forms.ImageField(label='Profile Picture', required=False)
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ProfileForm,self).__init__(*args, **kwargs)
        self.user = user

        if isinstance(user, Student):
            self.fields['student_id'].initial = user.student_id
            self.fields['staff_id'].widget = forms.HiddenInput()
            self.fields['staff_id'].required = False
            self.fields['student_id'].required = True
        elif isinstance(user, Staff):
            self.fields['staff_id'].initial = user.staff_id
            self.fields['student_id'].widget = forms.HiddenInput()
            self.fields['student_id'].required = False
            self.fields['staff_id'].required = True

        if 'password' in self.fields:
            del self.fields['password']
    class Meta:
        model = Student
        fields =['profile_pic', 'student_id', 'staff_id', 'name', 'email']

def clean_email(self):
    email = self.cleaned_data.get('email')
    if Student.objects.filter(email=email).exists():
        raise forms.ValidationError('Email is already taken')
    return email

def save(self, commit=True):
    user = self.user
    user.email = self.cleaned_data['email']
    user.name = self.cleaned_data['name']
    user.profile_pic = self.cleaned_data['profile_pic']
    
    if isinstance(user, Student):
       user.student_id = self.cleaned_data['student_id'] 
    elif isinstance(user, Staff):
        user.staff_id = self.cleaned_data['staff_id']
    if commit:
        user.save()
    return user

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput, required=True, min_length=8, max_length=16)
    new_password = forms.CharField(label='New Password', widget=forms.PasswordInput, required=True, min_length=8, max_length=16)
    confirm_password = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput, required=True, min_length=8, max_length=16)
   
    def __init__(self, user_type, user, *args, **kwargs):
        self.user_type = user_type
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if self.user_type == 'Student':
            self.user = Student.objects.get(id=self.user.id)
        elif self.user_type == 'Staff':
            self.user = Staff.objects.get(id=self.user.id)
        if old_password != self.user.password:
            raise forms.ValidationError('Old password is incorrect')
        return old_password
    
    def clean_new_password(self):
         new_password = self.cleaned_data.get('new_password')
        #  if new_password.isnumeric():
        #     raise forms.ValidationError('Password cannot be entirely number.')
         if not any(char.isdigit() for char in new_password):
                raise forms.ValidationError('Password must contain at least one number.')
         if not any(char.isalpha() for char in new_password):
                raise forms.ValidationError('Password must contain at least one alphabetic.')
         return new_password
    
    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')
        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError('New passwords do not match')
        return cleaned_data
    
    def save(self, commit=True):
        new_password = self.cleaned_data['new_password']
        if self.user_type == 'Student':
            self.user.password = new_password
        elif self.user_type == 'Staff':
            self.user.password = new_password
        if commit:
            self.user.save()    
        return self.user
from django import forms
from django.db.models import Q  # Import Q
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['class_code', 'date', 'time', 'end_time', 'guests', 'special_requests']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Retrieve 'user' from kwargs or set to None
        super().__init__(*args, **kwargs)
        self.user = user

        # Example of handling user-related data
        if user:
            if hasattr(user, 'student_id'):
                # Handle student-specific behavior
                pass
            elif hasattr(user, 'staff_id'):
                # Handle staff-specific behavior
                pass
            else:
                # Handle other cases or raise error
                pass

    def clean(self):
        cleaned_data = super().clean()
        class_code = cleaned_data.get('class_code')
        date = cleaned_data.get('date')
        time = cleaned_data.get('time')
        end_time = cleaned_data.get('end_time')

        # Ensure end time is after begin time
        if end_time <= time:
            raise forms.ValidationError('End time must be after begin time.')

        # Check for overlapping reservations
        overlapping_reservations = Reservation.objects.filter(
            class_code=class_code,
            date=date,
            is_cancelled=False
        ).exclude(
            Q(time__gte=end_time) | Q(end_time__lte=time)
        )

        if overlapping_reservations.exists():
            raise forms.ValidationError('This class is already reserved for the selected time.')

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.user:
            # Assign user to reservation instance based on logic
            if hasattr(self.user, 'student_id'):
                instance.student = self.user
            elif hasattr(self.user, 'staff_id'):
                instance.staff = self.user
            # Add other logic as needed

        if commit:
            instance.save()
        return instance
    
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['rating', 'review', 'facility']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.user = user
        
    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.user:
            if hasattr(self.user, 'student_id'):
                instance.student = self.user
            elif hasattr(self.user, 'staff_id'):
                instance.staff = self.user
        if commit:
            instance.save()
        return instance

main/templates/main/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CAMPUS ASSET MANAGER{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300;1,400&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <h1>CAMPUS ASSET MANAGER</h1>
        <button class="menu-toggle" aria-label="Toggle navigation">&#9776;</button>
    </header>

    <nav>
        <ul class="menu">
            <li><a href="{% url 'home' %}" class="{% if request.path == '/home/' %}active{% endif %}">Home</a></li>
            <li><a href="{% url 'facilities' %}" class="{% if request.path == '/facilities/' %}active{% endif %}">Facilities</a></li>
            <li><a href="{% url 'reservations' %}" class="{% if request.path == '/reservations/' %}active{% endif %}">Reservations</a></li>
            <li><a href="{% url 'reviews' %}" class="{% if request.path == '/reviews/' %}active{% endif %}">Reviews</a></li>
            <li>
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}" class="{% if request.path == '/profile/' %}active{% endif %}">{{ user.name }}</a> <a>|</a>
                    <form action="{% url 'logout' %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                {% else %}
                    <a href="{% url 'login' %}" class="{% if request.path == '/login/' %}active{% endif %}">Login</a> <a>|</a>
                    <a href="{% url 'register' %}" class="{% if request.path == '/register_student/' %}active{% endif %}">Register</a>
                {% endif %}
            </li>
        </ul>
    </nav>

    {% block content %}{% endblock %}

    <footer>
        <p>&copy; 2024 CAMPUS ASSET MANAGER</p>
    </footer>

    <script>
        document.querySelector('.menu-toggle').addEventListener('click', function() {
            document.querySelector('.menu').classList.toggle('open');
        });
    </script>
</body>
</html>

main/templates/main/changepassword.html
{% extends "main/base.html" %}

{% block title %}Change Password{% endblock %}
{% load static %}
{% block content %}
<!-- aaaa -->
<link rel="stylesheet" type="text/css" href="{% static 'css/changepassword.css' %}">
<div class="content-wrapper">
    <section class="background-section">
        <div class="content">
            <form method="POST" class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <!-- <div>
                {{ form.old_password.label_tag}}
                {{ form.old_password }}
                </div>
                {% if form.old_password.errors %}
                        <div class="error">{{ form.old_password.errors }}</div>
                {% endif %}
                
                <div>
                {{ form.new_password.label_tag }}
                {{ form.new_password }}
                </div>
                {% if form.new_password.errors %}
                        <div class="error">{{ form.new_password.errors }}</div>
                {% endif %}
                
                <div>
                {{ form.confirm_password.label_tag }}
                {{ form.confirm_password }}
                </div>
                {% if form.confirm_password.errors %}
                        <div class="error">{{ form.confirm_password.errors }}</div>
                {% endif %}
                -->
                <div class="help-text">
                    <ul>
                    <li>Password must be at least 8 characters long.</li>
                    <li>Password can't be entirely numeric.</li>
                </ul>
            </div> 
            <div class="buttons">
                <button type="submit" class="btn">Confirm</button>
                <button type="button" class="btnhelp" id="toggleHelp">?</button>
            </div>    
            </form>
        </div>
    </section>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
     document.getElementById('toggleHelp').addEventListener('click', function() {
        // console.log('toggleHelp button clicked');
        var helpText = document.querySelector('.help-text');
        // console.log(helpText);
        if(!helpText.style.display || helpText.style.display === 'none' ) {
            helpText.style.display = 'block';
        } else {
            helpText.style.display = 'none';
        }
    });
});
</script>
{% endblock %}

main/templates/main/classes.html
{% extends 'main/base.html' %}
{% block title %}Classes{% endblock %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/facilities.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <title>Classes</title>
    <style>
        /* CSS for hiding the reservation form initially */
        .alertmodal{
            background-color: #f44336;
            color: white;
            padding: 10px;
            margin-bottom: 15px;
            text-align: center;
            
        }

        .alertmodal a{
            color: white;
            text-decoration: underline;
            margin-left: 10px;
        }

        .alertmodal a:hover{
            
            text-decoration: none;
        }
        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0,0,0,0.4);
        }
    
        .modal-content {
            background-color: #fefefe;
            margin: 10% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 90%; /* Adjust width as needed */
            max-width: 600px; /* Set maximum width */
            height: 70%; /* Adjust height as needed */
            max-height: 700px; /* Set maximum height */
            overflow-y: auto; /* Enable vertical scrolling if content overflows */
        }
    
        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }
    
        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }

        /* Add a blur effect to the background when the modal is displayed */
        .blur {
            filter: blur(5px);
            -webkit-filter: blur(5px);
        }
        
        /* CSS for messages */
        .messages {
            margin: 10px 0;
        }

        .alert {
            padding: 15px;
            margin-bottom: 20px;
            border: 1px solid transparent;
            border-radius: 4px;
        }

        .alert.success {
            color: #3c763d;
            background-color: #dff0d8;
            border-color: #d6e9c6;
        }

        .alert.error {
            color: #a94442;
            background-color: #f2dede;
            border-color: #ebccd1;
        }

        .reviews-container{
            text-align: center;
        }
        .rev-button{
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }
        .reviews-container .rev-button:hover{
            text-decoration: none;
            color: white;
        }

        .stars {
        color: #ffffff;
        }

        .stars .fa-star {
            font-size: 30px;
        }

        .fa-star.checked {
            color: #ffd700; 
        }
    </style>
</head>
<body>

    <div class="content">
        <!-- Add any content you want to display over the background image -->
        <h2>Welcome to classes reservation</h2>
        <p>Classes reservation</p>
        
    </div>
    {% for facility in facilities %}
        <div class="reviews-container">
            <a href="{% url 'reviews' %}" class="rev-button">
                <span class="stars">
                    {% if facility.average_rating %}
                        {% for star in "12345" %}
                            {% if forloop.counter <= facility.average_rating %}
                                <span class="fa fa-star checked"></span>
                            {% else %}
                                <span class="fa fa-star"></span>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        No reviews yet
                    {% endif %}
                </span>
            </a>
        </div>
    {% endfor %}
    
    <div class="container">
        {% for i in '0123' %}
        <div class="class-item">
            <span style="font-size: 20px;">CNM100{{  i|add:1 }}</span>
            <div class="right-section">
                <p class="availability">Available</p>
                <button class="reserve" onclick="showModal('modal{{  i|add:1 }}','form{{  i|add:1 }}')">Reserve</button>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if user.is_authenticated %}
    <!-- Messages Block -->
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert {{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Reservation Form Modals -->
    {% for i in '0123' %}
    <div id="modal{{ i|add:1}}" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal('modal{{  i|add:1 }}')">&times;</span>
            <div id="form{{ i|add:1}}" class="reservation-form">
                <form action="{% url 'reservations' %}" method="post" onsubmit="return validateReservation('form{{ i|add:1}}')">
                    {% csrf_token %}
                    <label for="class_code{{ i|add:1}}" style="color: black;">Facility Code:</label><br>
                    <input type="text" id="class_code{{ i|add:1}}" name="class_code" value="CMN100{{ i|add:1}}"><br><br>

                    <label for="date{{ i|add:1}}" style="color: black;">Date of Reservation:</label><br>
                    <input type="date" id="date{{ i|add:1}}" name="date" required><br><br>

                    <label for="time{{ i|add:1}}" style="color: black;">Begin time of Reservation:</label><br>
                    <input type="time" id="time{{ i|add:1}}" name="time" required><br><br>

                    <label for="end_time{{ i|add:1}}" style="color: black;">End time of Reservation:</label><br>
                    <input type="time" id="end_time{{ i|add:1}}" name="end_time" required><br><br>

                    <label for="guests{{ i|add:1}}" style="color: black;">Guests:</label><br>
                    <input type="number" id="guests{{ i|add:1}}" name="guests" required><br><br>

                    <label for="special_requests{{ i|add:1}}" style="color: black;">Special Requests:</label><br>
                    <textarea id="special_requests{{ i|add:1}}" name="special_requests" rows="4" cols="50"></textarea><br><br>

                    <input type="submit" value="Submit Reservation">
                </form>
            </div>
            <!-- Add more forms for other facilities if needed -->
        </div>
    </div>
    {% endfor %}
    
    {% else %}
    <div class="alertmodal">
        Please log in to make a reservation.
    <a class="button" href="{% url 'login' %}">Login</a> <a>or</a> <a href="{% url 'register' %}">Sign Up</a>.
    </div>
    {% endif %}
    <a href="{% url 'facilities' %}"><button class="back-button">Back</button></a>
    <script>
        function showAlert(alertId)
        {
            document.getElementById(alertId).style.display = 'block';
            document.querySelector('.container').classList.add('blur');
        }
        function showModal(modalId,formId) {
            console.log(modalId,formId);
            document.getElementById(modalId).style.display = 'block';
            document.getElementById(formId).style.display = 'block';
            document.querySelector('.container').classList.add('blur');
        }

        function closeModal(modalId) {
            document.getElementById(modalId).style.display = 'none';
            var forms = document.getElementsByClassName('reservation-form');
            for (var i = 0; i < forms.length; i++) {
                forms[i].style.display = 'none';
            }
            document.querySelector('.container').classList.remove('blur');
        }

        function validateReservation(formId) {
            console.log(formId);
            var form = document.getElementById(formId);
            var date = form.querySelector('input[name="date"]').value;
            var time = form.querySelector('input[name="time"]').value;
            var endTime = form.querySelector('input[name="end_time"]').value;

            var today = new Date();
            var selectedDate = new Date(date);

            if (selectedDate < today.setHours(0,0,0,0)) {
                alert("The selected date is in the past. Please choose a valid date.");
                return false;
            }

            if (endTime <= time) {
                alert("End time must be after begin time.");
                return false;
            }

            return true;
        }
    </script>
    {% endblock %}
</body>
</html>

main/templates/main/facilities.html
{% extends 'main/base.html' %}

{% block title %}Reservations{% endblock %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/facilitiesmain.css' %}">
</head>

<body>
   
    <!-- Main content area -->
    <div class="content">
        <!-- Add any content you want to display over the background image -->
        <h2>Welcome to Reservations Manager</h2>
        <p>Choose a Facility from here</p>
    </div>

    <div class="container">
        {% if facilities %}
     
            {% for facility in facilities %}
            
                <div class="class-item">
                <a href="{% url 'facility_anemity' facility.anemity  %}" class="class-button">
                    <img src="{{ facility.image.url }}" alt="{{ facility.name }}">
                    {{ facility.name }}
                </a>
            </div>
    
            {% endfor %}
        {% else %}
            <p>No facilities found.</p>
        {% endif %}
    </div>
    {% endblock %}    
        <!-- <div class="class-item">
            <a href="{% url 'classes' %}" class="class-button">
                <img src="{% static 'imgs/Class.png' %}" alt="Classroom">
                Classes
            </a>
        </div>
        <div class="class-item">
            <a href="{% url 'classes' %}" class="class-button">
                <img src="{% static 'imgs/Lab.png' %}" alt="Classroom">
                 Labs
            </a>
        </div>
        <div class="class-item">
            <a href="{% url 'classes' %}" class="class-button">
                <img src="{% static 'imgs/Sport.png' %}" alt="Classroom">
                Sport Facilities
            </a>
        </div>
        <div class="class-item">
            <a href="{% url 'classes' %}" class="class-button">
                <img src="{% static 'imgs/Private.jpg' %}" alt="Classroom">
                Private Study Rooms
            </a>
        </div> -->
    

    
</body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/homepagestyle.css' %}">
</head>
<!-- Main content area -->
<div class="content-wrapper">
    <!-- New section for background image -->
    <section class="background-section">
        <div class="overlay-content">
            <!-- Add any content you want to display over the background image -->
            <h2>Welcome To Our Campus Reservation system</h2>
            <p>The best community that dedicated to student success for undergraduate, graduate and doctoral</p>
        </div>
    </section>
    <section class="campus" data-aos="fade-up">
        <div class="container">
            <div class="row">
                <div class="col-md-6" data-aos="fade-right">
                    <div class="campus-col">
                        <img src="{% static 'imgs/13.webp' %}" class="img-fluid" alt="Cyberjaya Campus">
                        <div class="layer">
                            <h3>Cyberjaya</h3>
                        </div>
                    </div>
                </div>
                <div class="col-md-6" data-aos="fade-left">
                    <div class="campus-col">
                        <img src="{% static 'imgs/melaka.webp' %}" class="img-fluid" alt="Melaka Campus">
                        <div class="layer">
                            <h3>Melaka</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="additional-content">
        <h1>START YOUR JOURNEY HERE</h1>
        <p>Where the best started here</p>
        <a href="{% url 'facilities' %}" class="reserve-button">Reserve your Facility</a>
    </div>
</div>

{% endblock %}

main/templates/main/profile.html
{% extends 'main/base.html' %}

{% block title %}Profile{% endblock %}
{% load static %}
{% block content %}
<script>
    window.onload = function () {
        document.getElementById('profile_pic').addEventListener('change', function (e) {
            const reader = new FileReader();
            reader.onload = function (e) {
                document.querySelector('.profile-pic img').src = e.target.result;
            }
            reader.readAsDataURL(this.files[0]);
        });
    };
</script>
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">


<div class="content-wrapper">
    <section class="background-section">
        <div class="content">
            <h2>Profile Settings</h2>
            <form method="POST"  enctype="multipart/form-data">
                {% csrf_token %}


                <div class="profile-container">
                    
                    
                    <div class="profile-pic">
                        <label for="profile_pic" class="icon-label" style="display:inline">
                            <img src="{% if user.profile_pic %}{{ user.profile_pic.url }}{% else %}{% static 'imgs/defaultpic.png' %}{% endif %}" alt="Profile Picture">
                        </label>
                        {{user_form.profile_pic}}
                        {{user_form.profile_pic.errors}}
                        <input type="file" name="profile_pic" id="profile_pic" accept="image/*" style="display: none;">
                        <label for="profile_pic" class="btn">Choose Profile Picture</label>
                    </div>   
                </div>
                
                <div class="form-group">
                    {% if user.staff_id %}
                    <div>
                    {{ user_form.staff_id.label_tag }}
                    <input type="text" name="staff_id" value="{{ user_form.staff_id.value }}" maxlength="200" readonly required id="id_staff_id">
                    {{ user_form.staff_id.errors }}
                    </div>
                    {% elif user.student_id %}
                    <div>
                    {{ user_form.student_id.label_tag }}
                    <input type="text" name="student_id" value="{{ user_form.student_id.value }}" maxlength="200" {% if not user.staff_id %}readonly{% endif %} required id="id_student_id">
                    {{ user_form.student_id.errors }}
                    </div>
                    {% endif %}
                    <div>
                    {{ user_form.name.label_tag }}
                    {{ user_form.name }}
                    {{ user_form.name.errors }}
                    </div>
                    <div>
                    {{ user_form.email.label_tag }}
                    {{ user_form.email }}
                    {{ user_form.email.errors }}
                </div>
                <a href="{% url 'changepassword' %}" class="btn">Change Password</a>
                </div>
                    
                    
           
                <button type="submit" class="btn">Update</button>
            </form>
        </div>
    </section>
</div>


{% endblock %}

main/templates/main/reviews.html
{% extends "main/base.html" %}

{% block title %}Reviews{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/reviews.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<div class="content-wrapper">
    <section class="background-section">
        <div class="content">
            <h2>Reviews</h2>
            {% if reviews %}
            <div class="reviews-list">
                {% for review in reviews %}
                <div class="reviews-item">
                    <div class="review-header">
                        {% if review.staff %}
                        <span class="review-id">{{ review.staff.staff_id }}</span>
                        {% elif review.student %}
                        <span class="review-id">{{ review.student.student_id }}</span>
                        {% endif %}
                        <span class="facility">{{ review.facility }}</span>
                        <span class="stars">
                            {% for star in "12345" %}
                                {% if forloop.counter <= review.rating %}
                                <span class="fa fa-star checked"></span>
                                {% else %}
                                <span class="fa fa-star"></span>
                                {% endif %}
                            {% endfor %}
                        </span>
                    </div>
                    <div class="review-comment">
                        {{ review.review }}
                    </div>
                </div>
                {% empty %}
                <p>No reviews found.</p>
                {% endfor %}
            </div>
            {% else %}
            <p>No reviews found.</p>
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}